apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-api
  namespace: ott
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ott-api
  template:
    metadata:
      labels:
        app: ott-api
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: api
          image: yny.ocir.io/axvqyylkrvmi/ott-api:3da3b4b607905d82c37e72d39e11d0ceb8bb1920
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: ott-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ott-api
  namespace: ott
spec:
  selector:
    app: ott-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
