apiVersion: v1
kind: Secret
metadata:
  name: ott-api-secrets
  namespace: ott
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://<DB_HOST>:5432/watchlog
  DB_USER: <DB_USER>
  DB_PASSWORD: <DB_PASSWORD>
  TMDB_ACCESS_TOKEN: <TMDB_ACCESS_TOKEN>
