apiVersion: v1
kind: Secret
metadata:
  name: ott-api-secrets
  namespace: ott
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://10.0.20.97:5432/watchlog
  DB_USER: watchlog
  DB_PASSWORD: watchlog
  TMDB_ACCESS_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkMzI0ZmJjYzZmZDNiOTRiMWI2OWQ4NWE3MzZmMGU4NSIsIm5iZiI6MTc0MTI0NjAwMC44MDQ5OTk4LCJzdWIiOiI2N2M5NGUzMDZmYjQwMDEzOTIwY2Q2MmYiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.WILOiYsUZDO99iWoJvYVlpN_u4fJYG7ZU4pK0SrJPGc 
  NAVER_CLIENT_ID: 3BPm5BPBqreJD1ddSwOH
  NAVER_CLIENT_SECRET: kp2_qlVXcE
