apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ott-ingress
  namespace: ott
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - ott.preview.pe.kr
      secretName: ott-preview-tls
  rules:
    - host: ott.preview.pe.kr
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ott-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ott-web
                port:
                  number: 3000
