apiVersion: v1
kind: Secret
metadata:
  name: ocir-pull-secret
  namespace: ott
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ5bnkub2Npci5pbyI6eyJ1c2VybmFtZSI6ImF4dnF5eWxrcnZtaS9haDJkaXVzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoibnRyYlQrKEg3LUY4X3ppWldsKWQiLCJlbWFpbCI6ImFoMmRpdXNAZ21haWwuY29tIiwiYXV0aCI6IllYaDJjWGw1Ykd0eWRtMXBMMkZvTW1ScGRYTkFaMjFoYVd3dVkyOXRPbTUwY21KVUt5aElOeTFHT0Y5NmFWcFhiQ2xrIn19fQ==
