apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-web
  namespace: ott
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ott-web
  template:
    metadata:
      labels:
        app: ott-web
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: web
          image: yny.ocir.io/axvqyylkrvmi/ott-web:2311c3055ecc2edb08c8f3dc9a5151e53b3ef0f7
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ott-web-config
---
apiVersion: v1
kind: Service
metadata:
  name: ott-web
  namespace: ott
spec:
  selector:
    app: ott-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  template:
    spec:
      containers:
        - image: yny.ocir.io/axvqyylkrvmi/ott-web:2311c3055ecc2edb08c8f3dc9a5151e53b3ef0f7
