apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-web
  namespace: ott
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ott-web
  template:
    metadata:
      labels:
        app: ott-web
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: web
          image: yny.ocir.io/axvqyylkrvmi/ott-web:0f5b0e16d756d29ff8af232c36755fcfde81333e
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ott-web-config
            - secretRef:
                name: ott-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ott-web
  namespace: ott
spec:
  selector:
    app: ott-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
